### ISSUE TITLE
Wrong Tagging for APZR

### ISSUE THREAD

**Issue by jban-x3** [rsennrich/ParZu#19]
Hi @rsennrich,

we're playing around with ParZu, which is really fun and awesome work.

But we find a small but important differnce between the output of your docker image and your online tool https://pub.cl.uzh.ch/demo/parzu/.

sentence: Eigentlich ist der von Geburt an perfekte Mann in der Lage, alles zu machen.

![failure](https://user-images.githubusercontent.com/48205656/53727228-f8ebb680-3e6f-11e9-889c-40ad58230282.png)

1. is the output of your online tool
2. is the docker image output

Could you image how this difference could appear. Doesn't github has the current version?

Thank you for your feedback

**Comment by jban-x3** [comment]
![bildschirmfoto 2019-03-04 um 13 55 18](https://user-images.githubusercontent.com/48205656/53734785-550d0580-3e85-11e9-861d-c3721161527b.png)
We found an other example where the online tool is wrong 
@rsennrich if you like we can post everything we'll find

**Comment by rsennrich** [comment]
The github repository and the online demo are slightly different in terms of the statistics files (see point 4 of the 'local installation' instructions), and in the model used for the POS-tagger. Generally, the TüBa statistics used in the demo should be slightly better. There may be an issue with orthography though... "muss" is not recognized as VMFIN by the online demo, but "muß" is.

**Comment by teufelmartin** [comment]
Thank you @rsennrich 
Don't you think for issue 1 it's not only a wrong grammar rule because the tagging result is the identical?

Do you have any ressources where to start to dig into the code of ParZu-parser.pl and grammar_german.pl

**Comment by rsennrich** [comment]
the tagging result is actually different in issue 1 as well (APZR vs. APPR for 'an'), so I think this is also the result of using a different tagger model.

**Comment by jban-x3** [comment]
delete my previous comment, because i posted with an account of my friend :(

Whicht tagger model do you use in your online demo?

**Comment by rsennrich** [comment]
if use use the `install.sh` script to setup ParZu, this will install clevertagger for POS tagging with a model trained on the Hamburg Dependency Treebank.

the online demo also uses clevertagger, but uses a model trained on TüBa-D/Z.

**Comment by jban-x3** [comment]
still working on our thesis, looking for a comprehensive description about grammar_german.pl. Do you have any idea where to find something like this? thanks a lot!

**Comment by rsennrich** [comment]
The syntactic annotation that ParZu is based on is described here (in German): http://edoc.sub.uni-hamburg.de/informatik/volltexte/2014/204/pdf/foth_eine_umfassende_.pdf

grammar_german.pl is the rule-based component of the parser, and I'm afraid there's no in-depth description of all the rules, and no way easy way of converting them into some other format.

Here is a short description from Sennrich et al. (2013) (https://www.aclweb.org/anthology/R13-1079.pdf):

> The hand-written grammar is mostly unlexicalized and operates on the level of parts-of-speech.
To give the subject relation as example, the grammar constrains the possible parts-of-speech of the head (a finite verb) and the dependent (typically a noun or pronoun, but some other classes such as numbers are also allowed). The dependent must be in nominative case, and either agree with the verb in person and number, or be a coordinated structure. Since each word form may have multiple possible morphological analyses, the morphological constraints are unification-based and allow for underspecified representations. Also, at most one subject is allowed per finite verb, and some topological restrictions must be met, such as only one constituent being allowed in the Vorfeld.
