### ISSUE TITLE
Run SWI-prolog from custom location

### ISSUE THREAD

**Issue by lefterav** [rsennrich/ParZu#3]
Hi again,

since the pre-installed version of swi-prolog is old, and our administrators are not willing to upgrade it with custom ways, I tried to compile version swi-prolog 7.1.27 myself. Unfortunately, although swi-prolog compiled fine, I cannot find which is the proper way to make parZu run with it. 

In particular, I tried two ways:
(a) modify parzu.py lines 25 and 30, in order to point to the exact location of swipl, e.g. /project/folder/software/swipl/swip . After this, parsing only gave me empty output. 
(b) modify $PATH variable of the system, so that 'swipl' command looks on the freshly compiled folder instead of /usr/bin/swipl (old version). This gives an error [FATAL ERROR:	Could not find system resources] which I am unable to fix, although I set $SWI_HOME_DIR both from commandline and inside the python script

could you please advise on how to proceed?
cheers
Lefteris

**Comment by dinosaxon** [comment]
Hi, 

I am trying to use ParZu but I get an empty output. I have read the above posts and tried with --output preprocessed and --output raw and it works. However, with --projective gives me an empty output. Actually, what I need to do is to run the wmt2014-scripts with EMS.

Thank you in advance for your help.

**Comment by rsennrich** [comment]
Hi Dinosaxon,

which version of swi-prolog are you using? (and if it's 7.2, do you use the latest version of ParZu?)
there might also be an error message that is printed to a log file (in ParZu/tmp/err*.pl) - so please check that and report if there is anything -  you might have to set 'deltemp = 0' in ParZu/config.ini.

If you're interested in having the WMT14/5 data parsed: I put parses for WMT14/15 data on http://statmt.org/rsennrich/parsed_wmt/ , so that you don't have to reparse. You still need to apply the enrich_labelset.py and create_moses_format.py scripts. Then, change the EMS to use 'clean-parsed-stem' instead of 'raw-stem' in the CORPUS section, and 'mock-parsed-corpus' instead of 'raw-corpus' in the LM sections, and point to the new files. I'll try to better document this.

**Comment by dinosaxon** [comment]
Hi,

Thank you for your prompt reply. Unfortunately, I cannot get the ParZu/tmp/err*.pl. I use the 7.2 version of swi-prolog in Ubuntu 12.04 with the latest ParZu.

I will try to run some more tests and let you know.

Regarding the already parsed sets: my aim is to built my own english-into-german engines so I should resolve this issue. On the other hand they will help me to understand how the output is and confirm that everything is okay.

Once again thank you for your time and consideration. I would appreciate if you can have a look into this even if you don't have more information about my installation.

Thanks

**Comment by arendu** [comment]
Hi, 
I seem to be getting the same error I have an old version of swipl (version 6.6.6, unfortunately I could not install 7.2.x on my machine due to some install errors)

I have linked swipl, swipl-ld and swipl-rc.

```shell
$>"Das is ein Test" | ./parzu
-bash: Das is ein Test: command not found
Starting tokenizer
Starting POS-tagger
Starting preprocessor
Tokenizer v3
Language: de
* Load model
* Label sequences
* Done
reading transducer from file "/home/arenduc1/source-pkgs/ParZu/external/zmorge-20140521-smor_newlemma.ca"...
finished.

Starting parser
Starting postprocessor
[FATAL ERROR:
	Could not find system resources]
[FATAL ERROR:
	Could not find system resources]
[FATAL ERROR:
	Could not find system resources]
[FATAL ERROR:
	Could not find system resources]
[FATAL ERROR:
	Could not find system resources]
```

**Comment by rsennrich** [comment]
You'll have to try to fix your swipl installation before running ParZu.  

Here's the relevant entry from the swipl homepage: http://www.swi-prolog.org/FAQ/FindResources.html
